image: python:latest

stages:
- test
- deploy

cache:
  paths:
    - ~/.cache/pip/

coverage:
  stage: test
  services:
    - postgres:latest
  before_script:
    - pip install -r requirements/tests.txt
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/{{project_name}}"
    DJANGO_SECRET_KEY: "{{secret_key}}"
  script:
    - flake8
    - coverage run manage.py test --settings={{project_name}}.settings --configuration=Testing --noinput
    - coverage html
    - coverage report -m
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 day

pages:
  stage: deploy
  before_script:
      - "true"
  dependencies:
    - coverage
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
