image: python:3.7

stages:
- test
- deploy

cache:
  paths:
    - ~/.cache/pip/

coverage:
  stage: test
  services:
    - postgres:11
  before_script:
    - pip install -r requirements/tests.txt
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/{{project_name}}"
    DJANGO_SECRET_KEY: "{{secret_key}}"
    DJANGO_SETTINGS_MODULE: "{{project_name}}.settings"
    DJANGO_CONFIGURATION: "Testing"
  script:
    - coverage run manage.py test --noinput
    - coverage html
    - coverage report -m
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 day

pages:
  stage: deploy
  before_script:
      - "true"
  dependencies:
    - coverage
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
