image: python:latest

services:
  - postgres:latest

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - pip install -r requirements/tests.txt

test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/{{project_name}}"
    DJANGO_SECRET_KEY: "{{secret_key}}"
  script:
    - make gitlabci
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
