image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        services:
          - postgres
        script:
          - pip install tox
          - export DATABASE_URL=postgres://postgres:postgres@localhost:5432/{{project_name}}
          - export DJANGO_SECRET_KEY=dj4ng0s3cr3tk3y
          - tox -e coverage,reportxml

definitions:
  services:
    postgres:
      image: postgres:12
      variables:
        POSTGRES_DB: '{{project_name}}'
        POSTGRES_PASSWORD: 'postgres'
