image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        services:
          - postgres
        script:
          - pip install -r requirements/tests.txt
          - export DATABASE_URL=postgres://postgres:postgres@localhost:5432/{{project_name}}
          - export DJANGO_SECRET_KEY={{secret_key}}
          - export DJANGO_SETTINGS_MODULE={{project_name}}.settings
          - export DJANGO_CONFIGURATION=Testing
          - coverage run manage.py test --noinput
          - coverage xml -o test-reports/coverage.xml

definitions:
  services:
    postgres:
      image: postgres:11
      variables:
        POSTGRES_DB: '{{project_name}}'
        POSTGRES_PASSWORD: 'postgres'
