vassal: beta
configuration: Beta
project_name: {{cookiecutter.project_slug}}
project_dir_name: {{cookiecutter.project_slug}}_beta
project_venv_name: {{cookiecutter.project_slug}}_beta
git_repository: servergit/{{cookiecutter.project_slug}}.git
db_name: {{cookiecutter.project_slug}}_beta
db_user: postgres
db_password: password
branch: develop
